name: MiniPlaceholders-Player-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.player.paper.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  - name: MiniPlaceholders
    required: true
